FROM ubuntu:18.04
# Run with `docker build --build-arg coda_deb_version=<version>`
ARG coda_deb_version
ARG deb_repo=stable

ENV DEBIAN_FRONTEND noninteractive
RUN echo "Building image with version $coda_deb_version"

COPY scripts/healthcheck-utilities.sh /healthcheck/utilities.sh
COPY scripts/daemon-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./entrypoints /entrypoint.d

# Dependencies
RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    curl \
    jq \
    strace \
    dumb-init \
    libssl1.1 \
    libprocps6 \
    libgmp10 \
    libgomp1 \
    libffi6 \
    apt-transport-https \
    ca-certificates \
    dnsutils \
    tzdata && \
  rm -rf /var/lib/apt/lists/*

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net $deb_repo main" > /etc/apt/sources.list.d/o1.list \
  && apt-get update \
  && apt-get install -y "mina-mainnet=$coda_deb_version"

WORKDIR /root

ENV CODA_TIME_OFFSET 0

ENTRYPOINT ["/usr/bin/dumb-init", "/entrypoint.sh"]
